on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Org Name'
        required: true
        default: 'Test Org'
        type: choice
        options:
        - Test Org
        - XXX Org
        - Deneme Org
      projectName:
        description: 'Project Name'
        required: true
      workItemType:
        description: 'Work Item Type'
        required: true
        default: 'User Story'
        type: choice
        options:
          - User Story
          - Feature
          - Bugs
      ruleType:
        description: 'Rule Type'
        required: true
        default: 'Mandatary Wrok ID'
        type: choice
        options:
          - Mandatory Work ID
          - Mandatory InvestmentDimension
          - StoryPointsPicklist
          - StoryPointsPicklistReverse
      stageCategory:
        description: 'Stage'
        required: true
        default: 'N/A'
        type: choice
        options:
          - N/A
          - InProgress
          - Complated
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    env:
        ORG: ${{ inputs.org }}
        PROJECTNAME: ${{ inputs.projectName }} 
        WROKITEMTYPE: ${{ inputs.workItemType }} 
        RULETYPE: ${{ inputs.ruleType }} 
        STATECATEGORY: ${{ inputs.stageCategory }}
    if: github.ref == 'refs/heads/main'    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install argparse          
          
      - name: Run Python script
        run: python parameter-test.py --org $ORG --projectName $PROJECTNAME --workItemType $WROKITEMTYPE --ruleType $RULETYPE --stageCategory $STATECATEGORY
        
